name: Breakfast Snack Taco
links:
  - https://www.youtube.com/watch?v=PBa09Z0scDA
categories: []
versions:
  - ingredients:
      - 2 eggs
      - chipotle garlic seasoning (or any)
      - low fat cheese (feta, mozarella)
      - low carb tortilla
    instructions:
      - Add oil spray to a small pan and add two eggs
      - Add seasoning to top, break the yolks and flip
      - Add cheese
      - Remove from pan and add to a tortilla
      - Add ketchup, roll, and fry seal closed
