name: Cheaper Beef and Broccoli
links:
  - https://youtu.be/JpcQPwbS5wc?si=_wGqBFOd7eQbWppG
categories: []
versions:
  - ingredients:
      - 1/4 cup water
      - 1/2 cup soy sauce
      - 1 Tbsp corn starch
      - 1 Tbsp brown sugar
      - 1 tsp ginger
      - 1 spoonful minced garlic
      - rice
      - 1 pound lean beef
      - 2 pound bag of frozen broccoli
    instructions:
      - Start the rice
      - microwave and drain the broccoli
      - mix water, soy sauce, corn starch, sugar, ginger and garlic to make a
        sauce
      - brown beef, move beef to the side and add broccoli to pan
      - Add sauce, let it simmer
      - Serve with rice
