name: African Chicken Peanut Stew
links:
  - https://www.simplyrecipes.com/recipes/african_chicken_peanut_stew/
categories:
  - Slow Cooker
versions:
  - ingredients:
      - Chicken (Thighs or wings or drums or all)
      - 1-2 onions, sliced
      - 3 sweet potatoes, cubed
      - Tomatoes, 1 can cruashed or whole ~15 oz
      - 1 quart chicken stock
      - ginger (3 inches, minced)
      - garlic (1 small bulb, minced)
      - 1 cup peanut butter
      - 1 cup peanuts
      - Kale (or any additional veggies)
      - 1 Tbsp ground coriander
      - 1 tsp cayenne
      - chopped cilantro (optional)
    instructions:
      - brown chicken in air fryer
      - Saute onions, then add ginger and garlic
      - Add tomatoes, sweet potatoes, chicken broth, peanut butter, peanuts and
        spices.  Stew for ~1 hour
      - Add chicken and let it finish, maybe 30 minutes
      - Put out chicken and de-bone / shred
      - immersion blender on rest of stew, add lots of salt and pepper
      - Add cilentra and chicken, let cook for 10 more minutes and serve
