name: Crock Pot Chicken Pasta
links:
  - https://www.youtube.com/watch?v=J0YBy4-7Mvk
categories: []
versions:
  - ingredients:
      - 4 chicken thighs or breasts
      - half box pasta
      - one jar pasta sauce
      - one jar alfredo sauce
    instructions:
      - Add chicken to crock pot, cook until shreddable
      - shred it, add the rest, mix, enjoy
