name: Pancakes
categories:
  - Breakfast
  - Favorite
links:
  - https://www.youtube.com/watch?v=IY5ykPd3coo
versions:
  - ingredients:
      - 2 Tablespoons butter
      - 2 Tablespoons sugar
      - 1 egg
      - splash vanilla
      - 1 heaped Tablespoon baking powder
      - water or milk
      - Flour, bread or regular (almond flour won't work)
    instructions:
      - Barely melt butter into big pyrex jug (~30 seconds)
      - Add sugar, whish with fork
      - Add egg and a splash of vanilla, 1 teaspoon of salt, 1 Tablespoon of
        baking powder, whisk together
      - Add liquid to fill to 2 cup line
      - Add flour, about 1 cup and a half, until consistency like pancakes, fold
        with liquid
