name: Halal Chicken and Rice
links:
  - https://www.youtube.com/watch?v=g728DTEUUlw
categories: []
versions:
  - name: Marinade chicken
    ingredients:
      - boneless skinless chicken thighs
      - olive oil
      - dried thyme
      - dried oregano
      - garlic powder
      - onion powder
      - green cardamom powder
      - turmeric
      - paprika
      - allspice
      - black pepper
      - lemon juice
    instructions:
      - Mix dry ingredients.  Use 1/2 in marinade and save the other half
      - Mix and marinate until you loose patience
  - name: Sauce
    ingredients:
      - mayo
      - plain yogurt
      - lemon juice
      - garlic powder
      - salt
      - (optional) dried flakes like parsley or oregano
    instructions:
      - mix
  - name: Chicken and rice
    ingredients:
      - rice
      - (optional) stock
    instructions:
      - Fry chicken in some oil, remove chicken when cooked
      - Add rest of seasoning mix, add some more oil, add rice, toast for a bit
      - Add water or stock, bring to a boil, cover and simmer
  - name: Serve
    ingredients:
      - Lettuce
      - Tomatoes
    instructions:
      - Dice lettuce and tomatoes
      - Serve chicken, rice, lettuce, tomatoes and sauce
