name: Smoked Turkey Leg
links: []
categories:
  - Slow Cooker
versions:
  - ingredients:
      - Smoked Turkey Leg
    instructions:
      - Literally just throw it in the slow cooker.  Nothing else needed
