name: Hidden Vegetables Pasta
links:
- https://youtube.com/shorts/gRE28EIPJwY?si=lKNJ5u6JcmvpKv75
categories: [ "Cold Weather" ]
versions:
- name: Roast veggies
  ingredients:
  - tomatoes (cherry tomatoes are great)
  - Onion, diced
  - Carrots, diced
  - Red bell pepper, diced
  - Zucchini, diced
  - Garlic (or garlic powder)
  - Olive oil
  - salt
  - black pepper
  - Italian seasoning
  instructions:
  - Combine everything, roast veggies in air fryer for 20 minutes at 375F
- name: cheese
  ingredients:
  - Store bought pasta sauce
  - feta
  instructions:
  - Add cheese.  Air fry for an additional 5 minutes
  - Blend
