name: Protein Pumpkin Bread
links:
  - https://www.youtube.com/watch?v=pIa8FoUk0zI
categories:
  - Dessert
versions:
  - name: Wet Ingrediets
    ingredients:
      - 2 (4) eggs, mix really well
      - 250g (500g) pumpkin puree
      - 85g (170g) greek yogurt
      - small amount vanilla extract
  - name: Dry Ingrediets
    ingredients:
      - 75g (150g) flour
      - 1 tsp (2 tsp) baking soda
      - 1 tsp (2 tsp) baking powder
      - 1 tsp (2 tsp) salt
      - 45g (90g) sugar substitute (Erythritol or monk fruit or other)
      - 2 (4) packets sweetener (Stevia, Spenda, etc)
      - 50g (100g) whey protein powder (vanilla preferred)
      - 1 tsp (2) pumpkin pie spice
  - instructions:
      - Add wet and dry ingredients to separate bowls
      - Mix wet and try together
      - Pour half of mixture into a separate bowl
      - "In one bowl, add the following:"
      - 12g (24) cocoa powder
      - cinnamon
      - cayenne
      - 2 (4) packets sweetener (Stevia, Splenda, etc)
      - Alternate pouring the mixtures into 1 (2) loaf pans
      - Optionally, cut and swirl with a knife in the loaf pan
      - Bake at 275 for 45 minutes
