name: Salad Dressing
links:
  - https://www.youtube.com/watch?v=puWE8yKa-tY
categories: []
versions:
  - ingredients:
      - 4 parts greek yogurt, by weight, to 1 part rice vinegar
      - Flavoring, lime juice, lemeon juice, herbs, PB powder
      - salt and pepper
      - Water to thin out
    instructions:
      - Don't make too much, better when fresh
