name: Leftover Chicken or Turkey Wraps
categories: []
versions:
  - ingredients:
      - chicken or turkey leftovers
      - pickles
      - pickled jalapenos
      - american cheese
      - barbeque sauce
      - wraps
    instructions: []
notes:
  - Great for leftover chicken or turkey
