name: Curried Lentil Soup
links:
  - https://justthedarnrecipe.com/curried-lentil-soup
categories:
  - to try
  - Cold Weather
versions:
  - ingredients:
      - 2 cups (250g) red lentils
      - 32 oz (1L) chicken broth
      - 2 cups (.5L) water
      - 2 tbsp (30ml) olive oil
      - 1/4 cup (60ml) heavy cream
      - 5 cloves garlic
      - 1 tablespoon (15ml) curry powder
      - 1 teaspoon (5ml) black pepper
      - 1 teaspoon (5ml) salt
    instructions:
      - Heat the olive oil in a stockpot over medium heat.
      - While the oil is heating up, mince the garlic then add to the pot.
      - Cook the garlic for approximately 2 minutes until toasted.
      - Add the lentils along with the chicken broth, water, curry powder, black
        pepper, and salt, then stir to combine.
      - Crank up the heat and bring to a simmer, then turn the heat down to low.
      - Cook for 20 minutes or until the lentils reach desired doneness (we
        prefer them slightly grainy).
      - Add the heavy cream, stir, and allow to cool slightly.
      - Garnish with olive oil, pepper, and green onions if you have them.
