name: Sweet and Sour Chicken
links:
  - https://www.youtube.com/watch?v=lxXN4JOX4ak
categories:
  - Chinese
versions:
  - ingredients:
      - Chicken Thighs, cut into bite sized pieces
      - 20oz can of pineapple slices
      - green pepper, diced
      - red food coloring
      - sugar, vinegar, cornstarch, baking powder, egg
  - name: Chicken Thighs
    instructions:
      - Make a batter with corn starch (about 1 cup), baking powder (1/2 tsp),
        salt, add water and whisk in egg to make batter-like consistency.
      - Coat chicken in batter and semi-deep fry in about 1 inch of oil
  - name: Finishing
    instructions:
      - Drain pineapple juice from can into saucepan, add sugar, vinegar, salt,
        red food coloring.  Separately combine cornstarch (2Tbsp) and water into
        slurry, add to sauce to thicken.  Heat sauce to simmer.
      - Add sauce, green pepper and pineapple to wok.  Don't cook too long, keep
        vegetables and chicken crispy
      - Serve with rice
