name: Everything Sauce
links:
  - https://www.youtube.com/watch?v=cNElghlPe54
categories: []
versions:
  - ingredients:
      - Sour Cream (2 cups)
      - Ketchup (1/2 cup)
      - Mayo (1/2 cup)
      - Worchestershire sauce (2 tablespoons)
      - veggie oil (2 tablespoons)
      - mustard (1 tablespoon)
      - garlic powder (1 teaspoon)
      - paprika (1 teaspoon)
      - seasoning salt (1 teaspoon)
    instructions: []
