name: Brazillian Lemonade
links:
  - https://www.youtube.com/watch?v=2hF_w7X4fEY
categories:
  - Dessert
versions:
  - ingredients:
      - 3 limes
      - sweetened condensed milk
    instructions:
      - wash and half three limes, add to blender with water
      - puree and strain out liquid
      - Add liquid, sweetened condensed milk and ice to blender
      - blend and enjoy
