name: Turkey Melt
categories: []
versions:
  - ingredients:
      - Sliced Turkey
      - Flatbread
      - Lettuce
      - Salad Dressing (Honey Mustard)
      - Sriracha
      - Shredded Cheese (cheddar)
    instructions:
      - Finely chop lettuce.  Add to bowl and mix with salad dressing
      - Place cheese on flatbread.  Place turkey on cheese.  Place lettuce on
        turkey
      - Fold in half and grill/press
