name: Cocoa Nut Almond Butter
categories:
  - Dessert
versions:
  - ingredients:
      - 2 tablespoons cocoa powder
      - 1/8 teaspoon salt
      - 1 1/4 cup almonds
      - 2 tablespoons coconut flakes
    instructions:
      - Add ingredients to blender twister jar.  Blend medium to medium high
        speed for 40 seconds
