name: Burger 'n Bean Hot Dish
links:
  - https://www.youtube.com/watch?v=oXWr23_GQ3U
categories:
  - Slow Cooker
versions:
  - ingredients:
      - Slow cooker liner
      - 1 16oz can barbecue beans (or regular beans plus barbecue sauce)
      - 1 11.5 oz can bean with bacon soup
      - 1/4 tsp black pepper
      - 1/4 tsp chili powder
      - 1/2 tsp garlic salt (garlic powder is fine)
      - 1 chopped onion
      - 1 pound ground beef
      - shredded cheese (american preferred, cheddar OK)
      - corn bread (optional)
    instructions:
      - Line slow cooker
      - combine all ingredients except ground beef and cheese
      - Cover and cook on low for 4 hours
      - Add beef one hour before done, break it up
      - Top with cheese and serve with corn bread
