name: Pizza Pockets
links:
  - https://www.youtube.com/watch?v=1v0hzuEZ3bg&t=44s
categories:
  - Favorite
versions:
  - ingredients:
      - turkey pepperoni
      - mozzarella cheese
      - flour tortillas
      - pizza sauce
    instructions:
      - Slice Pepperoni into shreds
      - Shred mozzarella into a bowl
      - Add basil and oregano to bowl
      - Make cones with tortillas, add pepperoni/cheese mixture, seal shut
      - spray with oil and cook in the air fryer at 375 for 10 minutes
      - Serve with pizza sauce for dipping
