name: Caramelized Onion Jam
links:
  - https://www.allrecipes.com/recipe/220546/onion-jam/
notes:
  - Great for leftover extra onions
categories:
  - Side Dish
versions:
  - ingredients:
      - 1/4 cup vegetable oil
      - 1/2 cup white sugar
      - 4 cups onion, coarsely chopped
      - 1/4 teaspoon salt
      - black pepper to taste
      - 1/2 cup red wine vinegar
    instructions:
      - Heat vegetable oil and sugar, stirring constantly until sugar is light
        brown, about 10 minutes.  Mixture will be very hot.
      - Add diced onions.  Stir constantly for about 15 minutes.
      - Pour red wine vinegar and let simmer until consistency is jam like,
        about 30 minutes
