name: Lasagna
links:
  - https://www.youtube.com/watch?v=ZlsrmJvk9f4
categories: []
versions:
  - ingredients:
      - 2 lbs 93% ground beef
      - 1 zucchini
      - shredded carrots
      - 1 red bell pepper
      - mushrooms
      - 1 shallot (or onion)
      - 3 cans of tomato sauce
      - 1 tsp salt
      - 1 tsp garlic powder
      - 2 tsp onion powder
      - 1 tsp black pepper
      - 2.5 tsp dried oregano*
      - 5 tsp dried basil*
      - 2 16 oz containers of 2% fat cottage cheese
      - 2 tbsp cornstarch
      - 2 large eggs (Grade A)
      - 1 cup skim shredded mozzarella cheese
      - 1 cup parmigian cheese (shredded or powdered)
      - 12 oz oven ready lasagna noodles
    instructions:
      - Preheat oven to 400F
      - Add veggies to food processor
      - Cook meat and veggies in large sauce pot
      - Add tomato sauce and spices to sauce pot
      - In a separate large bowl, add cottage cheese, eggs, and cornstarch.  Mix
        well
      - Add 1 cup shredded mozarella and parmesan to cheese bowl
      - In a casserole, add sauce, cheese, noodles, repeat, top with extra
        mozarella cheese
      - Cover in aluminum, put onto sheet, bake at 400F for 30 minutes
      - Finish uncovered at 450F
